plugins:
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  SuggestExtensions: false
  Exclude:
    - "vendor/bundle/**/*"
    - "tmp/**/*"
    - "*.gem"

Style/Documentation:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "lib/**/*"

Metrics/MethodLength:
  Max: 45
  Exclude:
    - "lib/deepiri_vizult/scanners/**/*"

Metrics/AbcSize:
  Max: 60

Metrics/ClassLength:
  Max: 200

Metrics/CyclomaticComplexity:
  Max: 25

Metrics/PerceivedComplexity:
  Max: 25

Metrics/ParameterLists:
  Enabled: false

Layout/LineLength:
  Max: 120
  AllowedPatterns:
    - '\A\s*#'

Naming/VariableNumber:
  Enabled: false

Naming/MethodParameterName:
  AllowedNames:
    - e
    - s
    - a
    - b
    - id
    - to

Lint/ShadowedException:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Max: 30

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - "spec/**/*"
