name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: true

      - name: Bundle install
        run: bundle install

      - name: RSpec
        run: bundle exec rspec

      - name: Gem build
        run: gem build deepiri-vizult.gemspec
